

# ALTER TABLE only allows constant defaults; timestamps are backfilled after add.
APPLICATIONS_SCHEMA_COLUMNS = (
    ("status", "TEXT NOT NULL DEFAULT 'New applicant'"),
    ("sub_status", "TEXT"),
    ("created_at", "TEXT"),
    ("updated_at", "TEXT"),
    ("risk_level", "TEXT NOT NULL DEFAULT 'Unassigned'"),
    ("approval_notes", "TEXT NOT NULL DEFAULT ''"),
    ("assigned_officer", "TEXT NOT NULL DEFAULT ''"),
    ("phone_number", "TEXT NOT NULL DEFAULT ''"),
    ("business_type", "TEXT NOT NULL DEFAULT ''"),
    ("date_of_birth", "TEXT"),
    ("gender", "TEXT NOT NULL DEFAULT ''"),
    ("flagged_fraud", "INTEGER NOT NULL DEFAULT 0"),
    ("loan_amount", "REAL"),
    ("underwriting_status", "TEXT NOT NULL DEFAULT 'pending_review'"),
    ("affordability_assessment", "TEXT NOT NULL DEFAULT 'not_assessed'"),
    ("repayment_confidence", "TEXT NOT NULL DEFAULT 'not_assessed'"),
    ("business_stability_review", "TEXT NOT NULL DEFAULT 'not_assessed'"),
    ("documentation_quality_review", "TEXT NOT NULL DEFAULT 'not_assessed'"),
    ("operational_risk_observations", "TEXT NOT NULL DEFAULT ''"),
    ("fraud_concern_observations", "TEXT NOT NULL DEFAULT ''"),
    ("underwriting_notes", "TEXT NOT NULL DEFAULT ''"),
    ("decision_summary", "TEXT NOT NULL DEFAULT ''"),
    ("decision_reason", "TEXT NOT NULL DEFAULT ''"),
    ("reviewed_by", "TEXT NOT NULL DEFAULT ''"),
    ("reviewed_at", "TEXT"),
    ("escalation_reason", "TEXT NOT NULL DEFAULT ''"),
    ("loan_lifecycle_status", "TEXT NOT NULL DEFAULT 'not_issued'"),
    ("loan_account_number", "TEXT NOT NULL DEFAULT ''"),
    ("issued_amount", "REAL"),
    ("outstanding_balance", "REAL"),
    ("repayment_progress", "REAL NOT NULL DEFAULT 0"),
    ("issue_date", "TEXT"),
    ("due_date", "TEXT"),
    ("installment_amount", "REAL"),
    ("repayment_frequency", "TEXT NOT NULL DEFAULT ''"),
    ("collections_notes", "TEXT NOT NULL DEFAULT ''"),
    ("missed_payment_observations", "TEXT NOT NULL DEFAULT ''"),
    ("repayment_risk_level", "TEXT NOT NULL DEFAULT 'current'"),
    ("last_payment_at", "TEXT"),
)
